# nixpacks.toml
[phases.setup]
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "python3.10 -m ensurepip",
  "python3.10 -m pip install --upgrade pip setuptools wheel",
  "python3.10 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python3.10 -m uvicorn main:app --host 0.0.0.0 --port $PORT"

