# nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "python310Packages.pip"]

[phases.install]
cmds = [
  "python3.10 -m pip install --no-cache-dir --upgrade pip",
  "python3.10 -m pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
