# nixpacks.toml
[phases.setup]
nixPkgs = ["python310", "gcc", "cmake"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "pip install torch==2.2.2",
  "pip install torch-geometric",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
